In [1]:
# from canvas import learn_game, play_game, human_interaction, move_arrowkeys, move_regression, move_classification
from torch_bc import AgentNetwork_Regression
import pickle
import pandas as pd
import random
import matplotlib.pyplot as plt
from canvas import play_game

from torchvision import transforms
from PIL import Image
import numpy as np

pygame 2.6.1 (SDL 2.28.4, Python 3.12.7)
Hello from the pygame community. https://www.pygame.org/contribute.html

In [2]:
def preprocess_to_movement(action):
    ## (right - left, up - down) for (dx, dy)
    
    return (int(action[3]) - int(action[2]), int(action[0]) - int(action[1]))
  
def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')
    
    
folder = "screenshots-obs-seq-1k-withcols-closeness"
# folder = "test"
df = pd.read_pickle(f'./datasets/{folder}/ss-info.pkl')
print(f"df shape: {df.shape}")

# df.iloc[122]
df
# df[df.index.str.contains("close")]
# fracDf = df.sample(frac=0.5)
# print(f"fracDf shape: {fracDf.shape}")

df shape: (190045, 6)

,agent_x,agent_y,target_x,target_y,action,closeness
ss-0-close-0-seq-0.png,460,319,375,250,"(-5, -5)",0
ss-0-close-0-seq-1.png,455,314,375,250,"(-5, -5)",0
ss-0-close-0-seq-2.png,450,309,375,250,"(-5, -5)",0
ss-0-close-0-seq-3.png,445,304,375,250,"(-5, -5)",0
ss-0-close-0-seq-4.png,440,299,375,250,"(-5, -5)",0
...,...,...,...,...,...,...
ss-999-close-5-seq-109.png,161,421,91,420,"(-5, 0)",5
ss-999-close-5-seq-110.png,156,421,91,420,"(-5, 0)",5
ss-999-close-5-seq-111.png,151,421,91,420,"(-5, 0)",5
ss-999-close-5-seq-112.png,146,421,91,420,"(-5, 0)",5
ss-999-close-5-seq-113.png,141,421,91,420,"(-5, 0)",5

In [6]:
import re
df["number"] = df.index.map(lambda s: int(re.search(r"ss-(\d+)-close-(\d+)-seq-(\d+).png", s)[1]))
df
# s = "ss-1-close-2-seq-3.png"
# cs = re.search(r"ss-(\d+)-close-(\d+)-seq-(\d+).png", s)
# cs[0]

closeness = {
      0: 0.001,
      1: 0.001,
      2: 0.001,
      3: 0.001,
      4: 0.001, ## 25
      5: 0.001, ##35
    }
sampledIndices = {c : np.random.choice(np.arange(0, 1000), size=int(frac * 1000)) for c, frac in closeness.items()}
from pprint import pprint
pprint(sampledIndices)
df
df.to_csv(f"./data.csv")

{0: array([374]),
 1: array([820]),
 2: array([801]),
 3: array([135]),
 4: array([486]),
 5: array([372])}

In [29]:
idx = 1
imageName = df.iloc[idx].name
s = re.search(r"ss-(\d+)-close-(\d+)-seq-(\d+).png", imageName)
nFrames = 5
seq = df[df.index.str.contains(f"ss-{int(s[1])}-close-{int(s[2])}-seq-")]
print(f"{len(seq) = }")

if len(seq) < nFrames:
      chosen = seq
else:
  i = random.randint(0, len(seq) - nFrames)
  chosen = seq[i: i + nFrames]
  
nMissing = nFrames - len(chosen)
if nMissing > 0:
  ## leave the zeros_like at the front
  chosen = ["empty" for _ in range(nMissing)] + chosen.index.to_list()
else: 
  chosen = chosen.index.to_list()
  
  
chosen

len(seq) = 8

['ss-0-close-0-seq-1.png',
 'ss-0-close-0-seq-2.png',
 'ss-0-close-0-seq-3.png',
 'ss-0-close-0-seq-4.png',
 'ss-0-close-0-seq-5.png']

In [19]:
xs = [1,2,3,4,5,6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
xs[-10:]

[8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [40]:
df.head()
normd = df.copy()
dxs = normd["action"].map(lambda x: x[0])
dys = normd["action"].map(lambda x: x[1])

def normalise(x, ss):
  return 2 * ((x - ss.min()) / (ss.max() - ss.min())) - 1

normd["action"] = normd["action"].apply(lambda x: (normalise(x[0], dxs), normalise(x[1], dys)))
normd.head()

,agent_x,agent_y,target_x,target_y,action,closeness
ss-0-close-0.png,281,255,261,219,"(-0.4, -0.8)",0
ss-1-close-0.png,169,551,137,527,"(-0.8, -0.6)",0
ss-2-close-0.png,372,16,343,10,"(-0.8, -0.19999999999999996)",0
ss-3-close-0.png,89,395,62,377,"(-0.8, -0.4)",0
ss-4-close-0.png,758,197,747,175,"(-0.4, -0.8)",0

In [41]:
norm_name = "ss-info-normalised"
normd.to_pickle(f'./datasets/{folder}/{norm_name}.pkl')

In [27]:
with open("./datasets/1k-targets.pkl", "rb") as f:
    targets = pickle.load(f)
targets

[((350, 89, 589, 211), (4, 2)),
 ((354, 91, 589, 211), (4, 2)),
 ((358, 93, 589, 211), (4, 2)),
 ((362, 95, 589, 211), (4, 2)),
 ((366, 97, 589, 211), (4, 2)),
 ((370, 99, 589, 211), (4, 2)),
 ((374, 101, 589, 211), (4, 2)),
 ((378, 103, 589, 211), (4, 2)),
 ((382, 105, 589, 211), (4, 2)),
 ((386, 107, 589, 211), (4, 2)),
 ((390, 109, 589, 211), (4, 2)),
 ((394, 111, 589, 211), (4, 2)),
 ((398, 113, 589, 211), (4, 2)),
 ((402, 115, 589, 211), (4, 2)),
 ((406, 117, 589, 211), (4, 2)),
 ((410, 119, 589, 211), (4, 2)),
 ((414, 121, 589, 211), (4, 2)),
 ((418, 123, 589, 211), (4, 2)),
 ((422, 125, 589, 211), (4, 2)),
 ((426, 127, 589, 211), (4, 2)),
 ((430, 129, 589, 211), (4, 2)),
 ((434, 131, 589, 211), (4, 2)),
 ((438, 133, 589, 211), (4, 2)),
 ((442, 135, 589, 211), (4, 2)),
 ((446, 137, 589, 211), (4, 2)),
 ((450, 139, 589, 211), (4, 2)),
 ((454, 141, 589, 211), (4, 2)),
 ((458, 143, 589, 211), (4, 2)),
 ((462, 145, 589, 211), (4, 2)),
 ((466, 147, 589, 211), (4, 2)),
 ((470, 149, 589, 211), (4, 2)),
 ((474, 151, 589, 211), (4, 2)),
 ((478, 153, 589, 211), (4, 2)),
 ((482, 155, 589, 211), (4, 2)),
 ((486, 157, 589, 211), (4, 2)),
 ((490, 159, 589, 211), (4, 2)),
 ((494, 161, 589, 211), (4, 2)),
 ((498, 163, 589, 211), (4, 2)),
 ((502, 165, 589, 211), (4, 2)),
 ((506, 167, 589, 211), (4, 2)),
 ((510, 169, 589, 211), (4, 2)),
 ((514, 171, 589, 211), (4, 2)),
 ((518, 173, 589, 211), (4, 2)),
 ((522, 175, 589, 211), (4, 2)),
 ((526, 177, 589, 211), (4, 2)),
 ((530, 179, 589, 211), (4, 2)),
 ((534, 181, 589, 211), (4, 2)),
 ((538, 183, 589, 211), (4, 2)),
 ((542, 185, 589, 211), (4, 2)),
 ((546, 187, 589, 211), (4, 2)),
 ((550, 189, 589, 211), (4, 2)),
 ((554, 191, 589, 211), (4, 2)),
 ((558, 193, 589, 211), (4, 2)),
 ((562, 195, 589, 211), (4, 2)),
 ((566, 197, 589, 211), (4, 2)),
 ((570, 199, 591, 445), (0, 4)),
 ((570, 203, 591, 445), (0, 4)),
 ((570, 207, 591, 445), (0, 4)),
 ((570, 211, 591, 445), (0, 4)),
 ((570, 215, 591, 445), (0, 4)),
 ((570, 219, 591, 445), (0, 4)),
 ((570, 223, 591, 445), (0, 4)),
 ((570, 227, 591, 445), (0, 4)),
 ((570, 231, 591, 445), (0, 4)),
 ((570, 235, 591, 445), (0, 4)),
 ((570, 239, 591, 445), (0, 4)),
 ((570, 243, 591, 445), (0, 4)),
 ((570, 247, 591, 445), (0, 4)),
 ((570, 251, 591, 445), (0, 4)),
 ((570, 255, 591, 445), (0, 4)),
 ((570, 259, 591, 445), (0, 4)),
 ((570, 263, 591, 445), (0, 4)),
 ((570, 267, 591, 445), (0, 4)),
 ((570, 271, 591, 445), (0, 4)),
 ((570, 275, 591, 445), (0, 4)),
 ((570, 279, 591, 445), (0, 4)),
 ((570, 283, 591, 445), (0, 4)),
 ((570, 287, 591, 445), (0, 4)),
 ((570, 291, 591, 445), (0, 4)),
 ((570, 295, 591, 445), (0, 4)),
 ((570, 299, 591, 445), (0, 4)),
 ((570, 303, 591, 445), (0, 4)),
 ((570, 307, 591, 445), (0, 4)),
 ((570, 311, 591, 445), (0, 4)),
 ((570, 315, 591, 445), (0, 4)),
 ((570, 319, 591, 445), (0, 4)),
 ((570, 323, 591, 445), (0, 4)),
 ((570, 327, 591, 445), (0, 4)),
 ((570, 331, 591, 445), (0, 4)),
 ((570, 335, 591, 445), (0, 4)),
 ((570, 339, 591, 445), (0, 4)),
 ((570, 343, 591, 445), (1, 4)),
 ((571, 347, 591, 445), (0, 4)),
 ((571, 351, 591, 445), (1, 4)),
 ((572, 355, 591, 445), (1, 4)),
 ((573, 359, 591, 445), (1, 4)),
 ((574, 363, 591, 445), (1, 4)),
 ((575, 367, 591, 445), (1, 4)),
 ((576, 371, 591, 445), (0, 4)),
 ((576, 375, 591, 445), (1, 4)),
 ((577, 379, 591, 445), (1, 4)),
 ((578, 383, 591, 445), (1, 4)),
 ((579, 387, 591, 445), (1, 4)),
 ((580, 391, 591, 445), (0, 4)),
 ((580, 395, 591, 445), (1, 4)),
 ((581, 399, 591, 445), (1, 4)),
 ((582, 403, 591, 445), (1, 4)),
 ((583, 407, 591, 445), (1, 4)),
 ((584, 411, 591, 445), (1, 4)),
 ((585, 415, 591, 445), (0, 4)),
 ((585, 419, 591, 445), (1, 4)),
 ((586, 423, 591, 445), (1, 4)),
 ((587, 427, 643, 286), (1, -4)),
 ((588, 423, 643, 286), (1, -4)),
 ((589, 419, 643, 286), (1, -4)),
 ((590, 415, 643, 286), (1, -4)),
 ((591, 411, 643, 286), (1, -4)),
 ((592, 407, 643, 286), (1, -4)),
 ((593, 403, 643, 286), (1, -4)),
 ((594, 399, 643, 286), (1, -4)),
 ((595, 395, 643, 286), (2, -4)),
 ((597, 391, 643, 286), (2, -4)),
 ((599, 387, 643, 286), (1, -4)),
 ((600, 383, 643, 286), (2, -4)),
 ((602, 379, 643, 286), (2, -4)),
 ((604, 375, 643, 286), (2, -4)),
 ((606, 371, 643, 286), (1, -4)),
 ((607, 367, 643, 286), (2, -4)),
 ((609, 363, 643, 286), (2, -4)),
 ((611, 359, 643, 286), (2, -4)),
 ((613, 355, 643, 286), (1, -4)),
 ((614, 351, 643, 286), (2, -4)),
 ((616, 347, 643, 286), (2, -4)),
 ((618, 343, 643, 286), (2, -4)),
 ((620, 339, 643, 286), (1, -4)),
 ((621, 335, 643, 286), (2, -4)),
 ((623, 331, 643, 286), (2, -4)),
 ((625, 327, 643, 286), (2, -4)),
 ((627, 323, 643, 286), (1, -4)),
 ((628, 319, 643, 286), (2, -4)),
 ((630, 315, 643, 286), (2, -4)),
 ((632, 311, 643, 286), (2, -4)),
 ((634, 307, 643, 286), (1, -4)),
 ((635, 303, 56, 325), (-4, 0)),
 ((631, 303, 56, 325), (-4, 0)),
 ((627, 303, 56, 325), (-4, 0)),
 ((623, 303, 56, 325), (-4, 0)),
 ((619, 303, 56, 325), (-4, 0)),
 ((615, 303, 56, 325), (-4, 0)),
 ((611, 303, 56, 325), (-4, 0)),
 ((607, 303, 56, 325), (-4, 0)),
 ((603, 303, 56, 325), (-4, 0)),
 ((599, 303, 56, 325), (-4, 0)),
 ((595, 303, 56, 325), (-4, 0)),
 ((591, 303, 56, 325), (-4, 0)),
 ((587, 303, 56, 325), (-4, 0)),
 ((583, 303, 56, 325), (-4, 0)),
 ((579, 303, 56, 325), (-4, 0)),
 ((575, 303, 56, 325), (-4, 0)),
 ((571, 303, 56, 325), (-4, 0)),
 ((567, 303, 56, 325), (-4, 0)),
 ((563, 303, 56, 325), (-4, 0)),
 ((559, 303, 56, 325), (-4, 0)),
 ((555, 303, 56, 325), (-4, 0)),
 ((551, 303, 56, 325), (-4, 0)),
 ((547, 303, 56, 325), (-4, 0)),
 ((543, 303, 56, 325), (-4, 0)),
 ((539, 303, 56, 325), (-4, 0)),
 ((535, 303, 56, 325), (-4, 0)),
 ((531, 303, 56, 325), (-4, 0)),
 ((527, 303, 56, 325), (-4, 0)),
 ((523, 303, 56, 325), (-4, 0)),
 ((519, 303, 56, 325), (-4, 0)),
 ((515, 303, 56, 325), (-4, 0)),
 ((511, 303, 56, 325), (-4, 0)),
 ((507, 303, 56, 325), (-4, 0)),
 ((503, 303, 56, 325), (-4, 0)),
 ((499, 303, 56, 325), (-4, 0)),
 ((495, 303, 56, 325), (-4, 0)),
 ((491, 303, 56, 325), (-4, 0)),
 ((487, 303, 56, 325), (-4, 0)),
 ((483, 303, 56, 325), (-4, 0)),
 ((479, 303, 56, 325), (-4, 0)),
 ((475, 303, 56, 325), (-4, 0)),
 ((471, 303, 56, 325), (-4, 0)),
 ((467, 303, 56, 325), (-4, 0)),
 ((463, 303, 56, 325), (-4, 0)),
 ((459, 303, 56, 325), (-4, 0)),
 ((455, 303, 56, 325), (-4, 0)),
 ((451, 303, 56, 325), (-4, 0)),
 ((447, 303, 56, 325), (-4, 0)),
 ((443, 303, 56, 325), (-4, 0)),
 ((439, 303, 56, 325), (-4, 0)),
 ((435, 303, 56, 325), (-4, 0)),
 ((431, 303, 56, 325), (-4, 0)),
 ((427, 303, 56, 325), (-4, 0)),
 ((423, 303, 56, 325), (-4, 0)),
 ((419, 303, 56, 325), (-4, 0)),
 ((415, 303, 56, 325), (-4, 0)),
 ((411, 303, 56, 325), (-4, 0)),
 ((407, 303, 56, 325), (-4, 0)),
 ((403, 303, 56, 325), (-4, 0)),
 ((399, 303, 56, 325), (-4, 0)),
 ((395, 303, 56, 325), (-4, 0)),
 ((391, 303, 56, 325), (-4, 0)),
 ((387, 303, 56, 325), (-4, 0)),
 ((383, 303, 56, 325), (-4, 0)),
 ((379, 303, 56, 325), (-4, 0)),
 ((375, 303, 56, 325), (-4, 0)),
 ((371, 303, 56, 325), (-4, 0)),
 ((367, 303, 56, 325), (-4, 0)),
 ((363, 303, 56, 325), (-4, 0)),
 ((359, 303, 56, 325), (-4, 0)),
 ((355, 303, 56, 325), (-4, 0)),
 ((351, 303, 56, 325), (-4, 0)),
 ((347, 303, 56, 325), (-4, 0)),
 ((343, 303, 56, 325), (-4, 0)),
 ((339, 303, 56, 325), (-4, 0)),
 ((335, 303, 56, 325), (-4, 0)),
 ((331, 303, 56, 325), (-4, 0)),
 ((327, 303, 56, 325), (-4, 0)),
 ((323, 303, 56, 325), (-4, 0)),
 ((319, 303, 56, 325), (-4, 0)),
 ((315, 303, 56, 325), (-4, 0)),
 ((311, 303, 56, 325), (-4, 0)),
 ((307, 303, 56, 325), (-4, 0)),
 ((303, 303, 56, 325), (-4, 0)),
 ((299, 303, 56, 325), (-4, 0)),
 ((295, 303, 56, 325), (-4, 0)),
 ((291, 303, 56, 325), (-4, 0)),
 ((287, 303, 56, 325), (-4, 0)),
 ((283, 303, 56, 325), (-4, 0)),
 ((279, 303, 56, 325), (-4, 0)),
 ((275, 303, 56, 325), (-4, 0)),
 ((271, 303, 56, 325), (-4, 0)),
 ((267, 303, 56, 325), (-4, 0)),
 ((263, 303, 56, 325), (-4, 0)),
 ((259, 303, 56, 325), (-4, 0)),
 ((255, 303, 56, 325), (-4, 0)),
 ((251, 303, 56, 325), (-4, 0)),
 ((247, 303, 56, 325), (-4, 0)),
 ((243, 303, 56, 325), (-4, 0)),
 ((239, 303, 56, 325), (-4, 0)),
 ((235, 303, 56, 325), (-4, 0)),
 ((231, 303, 56, 325), (-4, 0)),
 ((227, 303, 56, 325), (-4, 0)),
 ((223, 303, 56, 325), (-4, 0)),
 ((219, 303, 56, 325), (-4, 0)),
 ((215, 303, 56, 325), (-4, 0)),
 ((211, 303, 56, 325), (-4, 0)),
 ((207, 303, 56, 325), (-4, 0)),
 ((203, 303, 56, 325), (-4, 0)),
 ((199, 303, 56, 325), (-4, 0)),
 ((195, 303, 56, 325), (-4, 0)),
 ((191, 303, 56, 325), (-4, 0)),
 ((187, 303, 56, 325), (-4, 0)),
 ((183, 303, 56, 325), (-4, 0)),
 ((179, 303, 56, 325), (-4, 0)),
 ((175, 303, 56, 325), (-4, 0)),
 ((171, 303, 56, 325), (-4, 0)),
 ((167, 303, 56, 325), (-4, 0)),
 ((163, 303, 56, 325), (-4, 1)),
 ((159, 304, 56, 325), (-4, 0)),
 ((155, 304, 56, 325), (-4, 1)),
 ((151, 305, 56, 325), (-4, 1)),
 ((147, 306, 56, 325), (-4, 1)),
 ((143, 307, 56, 325), (-4, 1)),
 ((139, 308, 56, 325), (-4, 1)),
 ((135, 309, 56, 325), (-4, 0)),
 ((131, 309, 56, 325), (-4, 1)),
 ((127, 310, 56, 325), (-4, 1)),
 ((123, 311, 56, 325), (-4, 1)),
 ((119, 312, 56, 325), (-4, 1)),
 ((115, 313, 56, 325), (-4, 0)),
 ((111, 313, 56, 325), (-4, 1)),
 ((107, 314, 56, 325), (-4, 1)),
 ((103, 315, 56, 325), (-4, 1)),
 ((99, 316, 56, 325), (-4, 1)),
 ((95, 317, 56, 325), (-4, 1)),
 ((91, 318, 56, 325), (-4, 0)),
 ((87, 318, 56, 325), (-4, 1)),
 ((83, 319, 56, 325), (-4, 1)),
 ((79, 320, 56, 325), (-4, 1)),
 ((75, 321, 664, 423), (4, 0)),
 ((79, 321, 664, 423), (4, 0)),
 ((83, 321, 664, 423), (4, 0)),
 ((87, 321, 664, 423), (4, 0)),
 ((91, 321, 664, 423), (4, 0)),
 ((95, 321, 664, 423), (4, 0)),
 ((99, 321, 664, 423), (4, 0)),
 ((103, 321, 664, 423), (4, 0)),
 ((107, 321, 664, 423), (4, 0)),
 ((111, 321, 664, 423), (4, 0)),
 ((115, 321, 664, 423), (4, 0)),
 ((119, 321, 664, 423), (4, 0)),
 ((123, 321, 664, 423), (4, 0)),
 ((127, 321, 664, 423), (4, 0)),
 ((131, 321, 664, 423), (4, 0)),
 ((135, 321, 664, 423), (4, 0)),
 ((139, 321, 664, 423), (4, 0)),
 ((143, 321, 664, 423), (4, 0)),
 ((147, 321, 664, 423), (4, 0)),
 ((151, 321, 664, 423), (4, 0)),
 ((155, 321, 664, 423), (4, 0)),
 ((159, 321, 664, 423), (4, 0)),
 ((163, 321, 664, 423), (4, 0)),
 ((167, 321, 664, 423), (4, 1)),
 ((171, 322, 664, 423), (4, 1)),
 ((175, 323, 664, 423), (4, 1)),
 ((179, 324, 664, 423), (4, 0)),
 ((183, 324, 664, 423), (4, 1)),
 ((187, 325, 664, 423), (4, 1)),
 ((191, 326, 664, 423), (4, 1)),
 ((195, 327, 664, 423), (4, 1)),
 ((199, 328, 664, 423), (4, 1)),
 ((203, 329, 664, 423), (4, 0)),
 ((207, 329, 664, 423), (4, 1)),
 ((211, 330, 664, 423), (4, 1)),
 ((215, 331, 664, 423), (4, 1)),
 ((219, 332, 664, 423), (4, 1)),
 ((223, 333, 664, 423), (4, 0)),
 ((227, 333, 664, 423), (4, 1)),
 ((231, 334, 664, 423), (4, 1)),
 ((235, 335, 664, 423), (4, 1)),
 ((239, 336, 664, 423), (4, 1)),
 ((243, 337, 664, 423), (4, 1)),
 ((247, 338, 664, 423), (4, 0)),
 ((251, 338, 664, 423), (4, 1)),
 ((255, 339, 664, 423), (4, 1)),
 ((259, 340, 664, 423), (4, 1)),
 ((263, 341, 664, 423), (4, 1)),
 ((267, 342, 664, 423), (4, 0)),
 ((271, 342, 664, 423), (4, 1)),
 ((275, 343, 664, 423), (4, 1)),
 ((279, 344, 664, 423), (4, 1)),
 ((283, 345, 664, 423), (4, 1)),
 ((287, 346, 664, 423), (4, 1)),
 ((291, 347, 664, 423), (4, 0)),
 ((295, 347, 664, 423), (4, 1)),
 ((299, 348, 664, 423), (4, 1)),
 ((303, 349, 664, 423), (4, 1)),
 ((307, 350, 664, 423), (4, 1)),
 ((311, 351, 664, 423), (4, 0)),
 ((315, 351, 664, 423), (4, 1)),
 ((319, 352, 664, 423), (4, 1)),
 ((323, 353, 664, 423), (4, 1)),
 ((327, 354, 664, 423), (4, 1)),
 ((331, 355, 664, 423), (4, 1)),
 ((335, 356, 664, 423), (4, 0)),
 ((339, 356, 664, 423), (4, 1)),
 ((343, 357, 664, 423), (4, 1)),
 ((347, 358, 664, 423), (4, 1)),
 ((351, 359, 664, 423), (4, 1)),
 ((355, 360, 664, 423), (4, 0)),
 ((359, 360, 664, 423), (4, 1)),
 ((363, 361, 664, 423), (4, 1)),
 ((367, 362, 664, 423), (4, 1)),
 ((371, 363, 664, 423), (4, 1)),
 ((375, 364, 664, 423), (4, 1)),
 ((379, 365, 664, 423), (4, 0)),
 ((383, 365, 664, 423), (4, 1)),
 ((387, 366, 664, 423), (4, 1)),
 ((391, 367, 664, 423), (4, 1)),
 ((395, 368, 664, 423), (4, 1)),
 ((399, 369, 664, 423), (4, 0)),
 ((403, 369, 664, 423), (4, 1)),
 ((407, 370, 664, 423), (4, 1)),
 ((411, 371, 664, 423), (4, 1)),
 ((415, 372, 664, 423), (4, 1)),
 ((419, 373, 664, 423), (4, 0)),
 ((423, 373, 664, 423), (4, 1)),
 ((427, 374, 664, 423), (4, 1)),
 ((431, 375, 664, 423), (4, 1)),
 ((435, 376, 664, 423), (4, 1)),
 ((439, 377, 664, 423), (4, 1)),
 ((443, 378, 664, 423), (4, 0)),
 ((447, 378, 664, 423), (4, 1)),
 ((451, 379, 664, 423), (4, 1)),
 ((455, 380, 664, 423), (4, 1)),
 ((459, 381, 664, 423), (4, 1)),
 ((463, 382, 664, 423), (4, 0)),
 ((467, 382, 664, 423), (4, 1)),
 ((471, 383, 664, 423), (4, 1)),
 ((475, 384, 664, 423), (4, 1)),
 ((479, 385, 664, 423), (4, 1)),
 ((483, 386, 664, 423), (4, 1)),
 ((487, 387, 664, 423), (4, 0)),
 ((491, 387, 664, 423), (4, 1)),
 ((495, 388, 664, 423), (4, 1)),
 ((499, 389, 664, 423), (4, 1)),
 ((503, 390, 664, 423), (4, 1)),
 ((507, 391, 664, 423), (4, 0)),
 ((511, 391, 664, 423), (4, 1)),
 ((515, 392, 664, 423), (4, 1)),
 ((519, 393, 664, 423), (4, 1)),
 ((523, 394, 664, 423), (4, 1)),
 ((527, 395, 664, 423), (4, 1)),
 ((531, 396, 664, 423), (4, 0)),
 ((535, 396, 664, 423), (4, 1)),
 ((539, 397, 664, 423), (4, 1)),
 ((543, 398, 664, 423), (4, 1)),
 ((547, 399, 664, 423), (4, 1)),
 ((551, 400, 664, 423), (4, 0)),
 ((555, 400, 664, 423), (4, 1)),
 ((559, 401, 664, 423), (4, 1)),
 ((563, 402, 664, 423), (4, 1)),
 ((567, 403, 664, 423), (4, 1)),
 ((571, 404, 664, 423), (4, 1)),
 ((575, 405, 664, 423), (4, 0)),
 ((579, 405, 664, 423), (4, 1)),
 ((583, 406, 664, 423), (4, 1)),
 ((587, 407, 664, 423), (4, 1)),
 ((591, 408, 664, 423), (4, 1)),
 ((595, 409, 664, 423), (4, 0)),
 ((599, 409, 664, 423), (4, 1)),
 ((603, 410, 664, 423), (4, 1)),
 ((607, 411, 664, 423), (4, 1)),
 ((611, 412, 664, 423), (4, 1)),
 ((615, 413, 664, 423), (4, 0)),
 ((619, 413, 664, 423), (4, 1)),
 ((623, 414, 664, 423), (4, 1)),
 ((627, 415, 664, 423), (4, 1)),
 ((631, 416, 664, 423), (4, 1)),
 ((635, 417, 664, 423), (4, 1)),
 ((639, 418, 664, 423), (4, 0)),
 ((643, 418, 664, 423), (4, 1)),
 ((647, 419, 107, 544), (-4, 1)),
 ((643, 420, 107, 544), (-4, 1)),
 ((639, 421, 107, 544), (-4, 1)),
 ((635, 422, 107, 544), (-4, 1)),
 ((631, 423, 107, 544), (-4, 1)),
 ((627, 424, 107, 544), (-4, 1)),
 ((623, 425, 107, 544), (-4, 1)),
 ((619, 426, 107, 544), (-4, 1)),
 ((615, 427, 107, 544), (-4, 1)),
 ((611, 428, 107, 544), (-4, 1)),
 ((607, 429, 107, 544), (-4, 1)),
 ((603, 430, 107, 544), (-4, 1)),
 ((599, 431, 107, 544), (-4, 1)),
 ((595, 432, 107, 544), (-4, 1)),
 ((591, 433, 107, 544), (-4, 1)),
 ((587, 434, 107, 544), (-4, 1)),
 ((583, 435, 107, 544), (-4, 1)),
 ((579, 436, 107, 544), (-4, 1)),
 ((575, 437, 107, 544), (-4, 1)),
 ((571, 438, 107, 544), (-4, 1)),
 ((567, 439, 107, 544), (-4, 1)),
 ((563, 440, 107, 544), (-4, 1)),
 ((559, 441, 107, 544), (-4, 1)),
 ((555, 442, 107, 544), (-4, 1)),
 ((551, 443, 107, 544), (-4, 1)),
 ((547, 444, 107, 544), (-4, 1)),
 ((543, 445, 107, 544), (-4, 1)),
 ((539, 446, 107, 544), (-4, 1)),
 ((535, 447, 107, 544), (-4, 1)),
 ((531, 448, 107, 544), (-4, 1)),
 ((527, 449, 107, 544), (-4, 1)),
 ((523, 450, 107, 544), (-4, 1)),
 ((519, 451, 107, 544), (-4, 1)),
 ((515, 452, 107, 544), (-4, 1)),
 ((511, 453, 107, 544), (-4, 1)),
 ((507, 454, 107, 544), (-4, 1)),
 ((503, 455, 107, 544), (-4, 1)),
 ((499, 456, 107, 544), (-4, 1)),
 ((495, 457, 107, 544), (-4, 1)),
 ((491, 458, 107, 544), (-4, 1)),
 ((487, 459, 107, 544), (-4, 1)),
 ((483, 460, 107, 544), (-4, 1)),
 ((479, 461, 107, 544), (-4, 1)),
 ((475, 462, 107, 544), (-4, 1)),
 ((471, 463, 107, 544), (-4, 1)),
 ((467, 464, 107, 544), (-4, 1)),
 ((463, 465, 107, 544), (-4, 1)),
 ((459, 466, 107, 544), (-4, 1)),
 ((455, 467, 107, 544), (-4, 1)),
 ((451, 468, 107, 544), (-4, 1)),
 ((447, 469, 107, 544), (-4, 1)),
 ((443, 470, 107, 544), (-4, 1)),
 ((439, 471, 107, 544), (-4, 1)),
 ((435, 472, 107, 544), (-4, 1)),
 ((431, 473, 107, 544), (-4, 1)),
 ((427, 474, 107, 544), (-4, 1)),
 ((423, 475, 107, 544), (-4, 1)),
 ((419, 476, 107, 544), (-4, 1)),
 ((415, 477, 107, 544), (-4, 1)),
 ((411, 478, 107, 544), (-4, 1)),
 ((407, 479, 107, 544), (-4, 1)),
 ((403, 480, 107, 544), (-4, 1)),
 ((399, 481, 107, 544), (-4, 1)),
 ((395, 482, 107, 544), (-4, 1)),
 ((391, 483, 107, 544), (-4, 1)),
 ((387, 484, 107, 544), (-4, 1)),
 ((383, 485, 107, 544), (-4, 1)),
 ((379, 486, 107, 544), (-4, 1)),
 ((375, 487, 107, 544), (-4, 1)),
 ((371, 488, 107, 544), (-4, 1)),
 ((367, 489, 107, 544), (-4, 1)),
 ((363, 490, 107, 544), (-4, 1)),
 ((359, 491, 107, 544), (-4, 1)),
 ((355, 492, 107, 544), (-4, 1)),
 ((351, 493, 107, 544), (-4, 1)),
 ((347, 494, 107, 544), (-4, 1)),
 ((343, 495, 107, 544), (-4, 1)),
 ((339, 496, 107, 544), (-4, 1)),
 ((335, 497, 107, 544), (-4, 1)),
 ((331, 498, 107, 544), (-4, 1)),
 ((327, 499, 107, 544), (-4, 1)),
 ((323, 500, 107, 544), (-4, 0)),
 ((319, 500, 107, 544), (-4, 1)),
 ((315, 501, 107, 544), (-4, 1)),
 ((311, 502, 107, 544), (-4, 1)),
 ((307, 503, 107, 544), (-4, 1)),
 ((303, 504, 107, 544), (-4, 0)),
 ((299, 504, 107, 544), (-4, 1)),
 ((295, 505, 107, 544), (-4, 1)),
 ((291, 506, 107, 544), (-4, 1)),
 ((287, 507, 107, 544), (-4, 1)),
 ((283, 508, 107, 544), (-4, 1)),
 ((279, 509, 107, 544), (-4, 0)),
 ((275, 509, 107, 544), (-4, 1)),
 ((271, 510, 107, 544), (-4, 1)),
 ((267, 511, 107, 544), (-4, 1)),
 ((263, 512, 107, 544), (-4, 1)),
 ((259, 513, 107, 544), (-4, 0)),
 ((255, 513, 107, 544), (-4, 1)),
 ((251, 514, 107, 544), (-4, 1)),
 ((247, 515, 107, 544), (-4, 1)),
 ((243, 516, 107, 544), (-4, 1)),
 ((239, 517, 107, 544), (-4, 1)),
 ((235, 518, 107, 544), (-4, 0)),
 ((231, 518, 107, 544), (-4, 1)),
 ((227, 519, 107, 544), (-4, 1)),
 ((223, 520, 107, 544), (-4, 1)),
 ((219, 521, 107, 544), (-4, 1)),
 ((215, 522, 107, 544), (-4, 0)),
 ((211, 522, 107, 544), (-4, 1)),
 ((207, 523, 107, 544), (-4, 1)),
 ((203, 524, 107, 544), (-4, 1)),
 ((199, 525, 107, 544), (-4, 1)),
 ((195, 526, 107, 544), (-4, 1)),
 ((191, 527, 107, 544), (-4, 0)),
 ((187, 527, 107, 544), (-4, 1)),
 ((183, 528, 107, 544), (-4, 1)),
 ((179, 529, 107, 544), (-4, 1)),
 ((175, 530, 107, 544), (-4, 1)),
 ((171, 531, 107, 544), (-4, 0)),
 ((167, 531, 107, 544), (-4, 1)),
 ((163, 532, 107, 544), (-4, 1)),
 ((159, 533, 107, 544), (-4, 1)),
 ((155, 534, 107, 544), (-4, 1)),
 ((151, 535, 107, 544), (-4, 1)),
 ((147, 536, 107, 544), (-4, 0)),
 ((143, 536, 107, 544), (-4, 1)),
 ((139, 537, 107, 544), (-4, 1)),
 ((135, 538, 107, 544), (-4, 1)),
 ((131, 539, 107, 544), (-4, 1)),
 ((127, 540, 107, 544), (-4, 0)),
 ((123, 540, 535, 330), (4, -2)),
 ((127, 538, 535, 330), (4, -2)),
 ((131, 536, 535, 330), (4, -2)),
 ((135, 534, 535, 330), (4, -2)),
 ((139, 532, 535, 330), (4, -2)),
 ((143, 530, 535, 330), (4, -2)),
 ((147, 528, 535, 330), (4, -2)),
 ((151, 526, 535, 330), (4, -2)),
 ((155, 524, 535, 330), (4, -2)),
 ((159, 522, 535, 330), (4, -2)),
 ((163, 520, 535, 330), (4, -2)),
 ((167, 518, 535, 330), (4, -2)),
 ((171, 516, 535, 330), (4, -2)),
 ((175, 514, 535, 330), (4, -2)),
 ((179, 512, 535, 330), (4, -2)),
 ((183, 510, 535, 330), (4, -2)),
 ((187, 508, 535, 330), (4, -2)),
 ((191, 506, 535, 330), (4, -2)),
 ((195, 504, 535, 330), (4, -2)),
 ((199, 502, 535, 330), (4, -2)),
 ((203, 500, 535, 330), (4, -2)),
 ((207, 498, 535, 330), (4, -2)),
 ((211, 496, 535, 330), (4, -2)),
 ((215, 494, 535, 330), (4, -2)),
 ((219, 492, 535, 330), (4, -2)),
 ((223, 490, 535, 330), (4, -2)),
 ((227, 488, 535, 330), (4, -2)),
 ((231, 486, 535, 330), (4, -2)),
 ((235, 484, 535, 330), (4, -2)),
 ((239, 482, 535, 330), (4, -2)),
 ((243, 480, 535, 330), (4, -2)),
 ((247, 478, 535, 330), (4, -2)),
 ((251, 476, 535, 330), (4, -2)),
 ((255, 474, 535, 330), (4, -2)),
 ((259, 472, 535, 330), (4, -2)),
 ((263, 470, 535, 330), (4, -2)),
 ((267, 468, 535, 330), (4, -2)),
 ((271, 466, 535, 330), (4, -2)),
 ((275, 464, 535, 330), (4, -2)),
 ((279, 462, 535, 330), (4, -2)),
 ((283, 460, 535, 330), (4, -2)),
 ((287, 458, 535, 330), (4, -2)),
 ((291, 456, 535, 330), (4, -2)),

In [37]:
fracs = {
  0: 0.25,
  1: 0.25,
  2: 1
}
gs = [df[df["closeness"] == c].sample(frac=frac) for c, frac in fracs.items()]
   

final = pd.concat(gs)
final

                  agent_x  agent_y  target_x  target_y    action  closeness
ss-2-close-0.png      103      528       137       550    (4, 2)          0
ss-0-close-1.png      507      541       419       359  (-2, -4)          1
ss-0-close-2.png      257       12       642       515    (3, 3)          2
ss-3-close-2.png      230       33       580        41    (4, 0)          2
ss-1-close-2.png       56      107       371       233    (4, 1)          2
ss-2-close-2.png      716      150       690       377    (0, 4)          2

In [22]:
with open("./datasets/1k-targets-mirrored.pkl", "wb") as f:
    pickle.dump(mirrored, f)

In [3]:
import re
df["number"] = df.index.map(lambda s: int(re.search(r"ss-(\d+)-close-(\d+)-seq-(\d+).png", s)[1]))
df
# s = "ss-1-close-2-seq-3.png"
# cs = re.search(r"ss-(\d+)-close-(\d+)-seq-(\d+).png", s)
# cs[0]

closeness = {
      0: 0.001,
      1: 0.001,
      2: 0.001,
      3: 0.001,
      4: 0.001, ## 25
      5: 0.001, ##35
    }
sampledIndices = {c : np.random.choice(np.arange(0, 1000), size=int(frac * 1000)) for c, frac in closeness.items()}
from pprint import pprint
pprint(sampledIndices)
df

{0: array([533]),
 1: array([933]),
 2: array([570]),
 3: array([770]),
 4: array([38]),
 5: array([164])}

,agent_x,agent_y,target_x,target_y,action,closeness,number
ss-0-close-0-seq-0.png,460,319,375,250,"(-5, -5)",0,0
ss-0-close-0-seq-1.png,455,314,375,250,"(-5, -5)",0,0
ss-0-close-0-seq-2.png,450,309,375,250,"(-5, -5)",0,0
ss-0-close-0-seq-3.png,445,304,375,250,"(-5, -5)",0,0
ss-0-close-0-seq-4.png,440,299,375,250,"(-5, -5)",0,0
...,...,...,...,...,...,...,...
ss-999-close-5-seq-109.png,161,421,91,420,"(-5, 0)",5,999
ss-999-close-5-seq-110.png,156,421,91,420,"(-5, 0)",5,999
ss-999-close-5-seq-111.png,151,421,91,420,"(-5, 0)",5,999
ss-999-close-5-seq-112.png,146,421,91,420,"(-5, 0)",5,999
ss-999-close-5-seq-113.png,141,421,91,420,"(-5, 0)",5,999

In [5]:
# print(df["number"] == 0)
gs = [df[(df["closeness"] == c) & (df["number"].isin(sampledIndices[c]))] for c, _ in closeness.items()]
together = pd.concat(gs)
print(together.shape)
together.to_csv(f"./togethersmall.csv")

(156, 7)

:

In [63]:
from torch_bc import PositionDataset

transform = transforms.Compose([
    transforms.ToTensor()
])

ss = "./datasets/ss-1k"
img = f"{ss}/ss-0.png"

demo = Image.open(img) 
# print(f"Image size: {demo.size}")

# demo_img = transform(demo)
# import torchvision
plt.imshow(demo)
# print(demo.getbands())
# torchvision.transforms.functional.to_pil_image(demo_img, mode=None)
# demo_array = demo_img.numpy()*255
# print(Image.fromarray(demo_array.astype(np.uint8)))
# plt.imshow(demo_img, cmap='gray')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KUP\\Desktop\\Code\\fyp\\src\\2d\\datasets\\ss-1k\\ss-0.png'

In [ ]:
image = play_game(moveAgent="move_cnn", model=AgentNetwork_Regression())
plt.imshow(image)

In [ ]:
dataset[1]

In [ ]:
# import matplotlib.pyplot as plt
# from tqdm import tqdm as progress

# params = {
#   "datasize": [100, 200, 500, 700, 1000],
#   "epochs": [10, 50, 100, 200],
#   "lr": [0.001, 0.01, 0.1],
#   "batch_size": [32, 64, 128],
#   "neurons": [32, 64, 128, 256],
# }

# results = {}

# for size in params["datasize"]:
  
#   modelName = f"regression-{"1k" if size == 1000 else size}.pth"
#   with open("./datasets/1k-targets.pkl", "rb") as f:
#     data = pickle.load(f)

#   points = int(len(data) * (size / 1000))  
#   samples = random.sample(data, points)
#   for epoch in (params["epochs"]):
#     for lr in params["lr"]:
#       for batchSize in params["batch_size"]:
#         for neurons in params["neurons"]:
#           print(f"### size: {size}, epoch: {epoch}, lr: {lr}, batchSize: {batchSize}, neurons: {neurons}")
          
#           model = AgentNetwork_Regression(epochs=epoch, lr=lr, batchSize=batchSize, npl=neurons).train_on_behaviour(data=samples, overwriteDevice="cpu", doPrints=False)
#           results[(size, epoch, lr, batchSize, neurons)] = model.get_training_losses()

In [ ]:
results